-- 한줄 주석
/*범위주석*/

CREATE TABLE "USER"(
	NAME VARCHAR2(500),
	AGE NUMBER
);

DROP TABLE "USER";

/*
 * 자동차 테이블 생성
 * 		자동차 번호
 * 		자동차 브랜드
 * 		출시 날짜
 * 		색상
 * 		가격
 * */
CREATE TABLE TBL_CAR(
	CAR_NUMBER NUMBER PRIMARY KEY,
	CAR_BRAND VARCHAR2(1000),
	CAR_RELEASE_DATE DATE,
	CAR_COLOR VARCHAR2(1000),
	PRICE NUMBER(5)
);

/*특정 테이블의 컬럼에 제약조건 추가*/
ALTER TABLE TBL_CAR ADD CONSTRAINT PK_CAR PRIMARY KEY(CAR_NUMBER);

/*특정 테이블의 컬럼에 제약조건 삭제*/
ALTER TABLE TBL_CAR DROP CONSTRAINT PK_CAR;
ALTER TABLE TBL_CAR DROP CONSTRAINT SYS_C007115;

DROP TABLE TBL_CAR;

/*
 * 동물 테이블 생성
 * 		고유 번호
 * 		종류
 * 		나이
 * 		먹이 VARCAHR2()
 * */
CREATE TABLE TBL_ANIMAL(
	ANIMAL_NUMBER NUMBER,
	ANIMAL_TYPE VARCHAR2(500),
	ANIMAL_AGE NUMBER(3),
	ANIMAL_FEED VARCHAR2(500)
);

/*제약조건 추가(PK)*/
ALTER TABLE TBL_ANIMAL ADD CONSTRAINT PK_ANIMAL PRIMARY KEY(ANIMAL_NUMBER);

/*제약조건 삭제(PK)*/
ALTER TABLE TBL_ANIMAL DROP CONSTRAINT PK_ANIMAL;

/*컬럼 추가(성별 CHAR(1))*/
ALTER TABLE TBL_ANIMAL ADD (ANIMAL_GENDER CHAR(1));

/*컬럼 이름 수정*/
ALTER TABLE TBL_ANIMAL RENAME COLUMN ANIMAL_TYPE TO ANIMAL_KIND;

/*컬럼 삭제(성별)*/
ALTER TABLE TBL_ANIMAL DROP COLUMN ANIMAL_GENDER;

/*컬럼 수정(먹이 컬럼의 타입을 NUMBER로)*/
ALTER TABLE TBL_ANIMAL MODIFY(ANIMAL_FEED NUMBER);
ALTER TABLE TBL_ANIMAL MODIFY(ANIMAL_FEED VARCHAR2(500));

/*동물 테이블 삭제*/
DROP TABLE TBL_ANIMAL;

/*
 * 학생 테이블 생성
 * 		학생 번호
 * 		학생 아이디
 * 		학생 이름
 * 		전공
 * 		성별-CHAR
 *		생년월일 
 * */
/*CONSTRAINT 명령어로 제약조건을 추가할 때에는 반드시 이름을 작성해야 한다.*/
/*제약조건의 이름을 작성하고 싶지 않다면 CONSTRAINT를 작성하면 안된다.*/
CREATE TABLE TBL_STUDENT(
	STUDENT_NUMBER NUMBER /*PRIMARY KEY*/,
	STUDENT_ID VARCHAR2(500) /*UNIQUE*/,
	STUDENT_NAME VARCHAR2(500),
	STUDENT_MAJOR VARCHAR(500),
	STUDENT_GENDER CHAR(1) DEFAULT 'F' NOT NULL CHECK(STUDENT_GENDER IN('M', 'F')), /*값을 추가하지 않으면 F, NULL 안됨, 성별은 M 또는 F만 가능*/
	STUDENT_BIRTH DATE CONSTRAINT BAN_BIRTH CHECK(STUDENT_BIRTH >= TO_DATE('1988-01-01', 'YYYY-MM-DD'))/*1987년생 이후 출생자만 가능*/
);

--PK는 학생 번호로 설정한다.
ALTER TABLE TBL_STUDENT ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STUDENT_NUMBER);

--컬럼 이름 수정
ALTER TABLE TBL_STUDENT RENAME COLUMN STUDENT_ID TO STUDENT_CODE;

--컬럼 추가
--남친여친유무 컬럼 추가
ALTER TABLE TBL_STUDENT ADD (STUDENT_COUPLE CHAR(1));

--유니크 키 추가
ALTER TABLE TBL_STUDENT ADD CONSTRAINT UK_STUDENT UNIQUE(STUDENT_CODE);

DROP TABLE TBL_STUDENT;
















