CREATE SEQUENCE SEQ_BOARD;

CREATE TABLE TBL_BOARD(
	BOARD_NUMBER NUMBER,
	BOARD_TITLE VARCHAR2(1000),
	BOARD_CONTENT VARCHAR2(2000),
	BOARD_WRITER VARCHAR2(1000),
	BOARD_REGISTER_DATE DATE DEFAULT SYSDATE,
	BOARD_UPDATE_DATE DATE DEFAULT SYSDATE,
	CONSTRAINT PK_BOARD PRIMARY KEY(BOARD_NUMBER) 
);

SELECT * FROM TBL_BOARD;

INSERT INTO TBL_BOARD (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
VALUES (SEQ_BOARD.NEXTVAL, '테스트 제목5', '테스트 내용5', 'user05');

INSERT INTO TBL_BOARD (BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER)
(SELECT SEQ_BOARD.NEXTVAL, BOARD_TITLE, BOARD_CONTENT, BOARD_WRITER FROM TBL_BOARD);

