/*시퀀스
 * 
 * 원하는 시작점을 설정할 수 있고, N씩 증가하는 값이다.
 * 기본 시작점은 1이고 기본 증가량은 1이다.
 * 
 * 다음 시퀀스를 가져올 때에는 시퀀스명.NEXTVAL
 * */

CREATE SEQUENCE SEQ_USER;
/*START WITH 3*/

DROP TABLE TBL_USER;

CREATE TABLE TBL_USER(
   USER_NUMBER NUMBER PRIMARY KEY,
   USER_ID VARCHAR2(1000) UNIQUE,
   USER_PW VARCHAR2(1000),
   USER_NAME VARCHAR2(1000),
   USER_AGE NUMBER,
   USER_PHONE_NUMBER VARCHAR2(1000),
   STATUS NUMBER DEFAULT 0
);

SELECT * FROM TBL_USER;

INSERT INTO TBL_USER (USER_NUMBER, USER_ID, USER_PW, USER_NAME, USER_AGE, USER_PHONE_NUMBER)
VALUES(SEQ_USER.NEXTVAL, 'hds1234', '1234', '한동석', '20', '01012341234');


SELECT * FROM TBL_USER
WHERE USER_ID = 'hds1234' AND USER_PW = '1234';
